// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:9882e51d-3ca0-44eb-9efa-11968a33313d",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_ZBIIWlyeF",
  aws_user_pools_web_client_id: "43id8sr138le9b3ops3fg8c4qg",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://yl3l26ohfbgwdkiklggwchozpe.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS"
};

export default awsmobile;
